# Generated by Django 4.1.2 on 2022-10-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='pub_date',
        ),
    ]
